name: Check

on:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run check
